services:
  - type: web
    name: issue-management-system
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: RECAPTCHA_SECRET
        sync: false
      - key: APP_BASE_URL
        sync: false

databases:
  - name: issue-manage-db
    databaseName: issuemanagedb
    user: postgres
    plan: free
    region: singapore
